version: "3"

services:
  # wordpress container
  location:
    container_name: location
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: dev
      WORDPRESS_DB_NAME: location
    ports:
      - 80

networks:
  default:
    external:
      name: docker_wordpress
