version: '3'

services:
  wp:
    container_name: wp
    build: .
    image: cmdev/wp-theme:latest
    ports:
      - 8082:80
    volumes:
      - ./dist:/var/www/html/wp-content/themes/collinscode
      - ./plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_NAME: "${DB_NAME:-collinscode}"
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD:-password}"
    networks:
      - collinscode

  db:
    container_name: db
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME:-collinscode}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
    ports:
      - 13311:3306
    networks:
      - collinscode

networks:
  collinscode:
    external: true

volumes:
  db_data:
