version: "3"

services:
  # wordpress container
  PROJ_NAME:
    container_name: PROJ_NAME
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: dev
      WORDPRESS_DB_NAME: PROJ_NAME

networks:
  default:
    external:
      name: docker_iostudio
